# Generated by Django 4.2.11 on 2024-04-08 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'Nit')], max_length=100, null=True)),
                ('identification', models.CharField(max_length=12)),
                ('enter_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('position', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('indicative', models.CharField(max_length=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_employee', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_employee', to='employee.employee')),
            ],
        ),
    ]
